export const GLOBAL_MESSAGE = {
  BAD_REQUEST: 'Bad Request',
  URL_NOT_FOUND: 'URL Not Found',
  INTERNAL_SERVER_ERROR: 'Internal Server Error',
  UNAUTHORIZED: 'Unauthorized',
  FORBIDDEN: 'Forbidden',
  CONFLICT: 'Conflict',
  NOT_FOUND: 'Not Found',
  UNPROCESSABLE_ENTITY: 'Unprocessable Entity',
  VALIDATION_ERROR: 'Validation Error',
  SERVER_ERROR: 'Server Error',
  BAD_GATEWAY: 'Bad Gateway',
  SERVICE_UNAVAILABLE: 'Service Unavailable',
  GATEWAY_TIMEOUT: 'Gateway Timeout',
  MISSING_REQUIRED_ENVIRONMENT_VARIABLES: 'Missing required environment variables for database configuration',
  REQUEST_TIMEOUT: 'Request Timeout',
};

export const SUCCESS_MESSAGE = {
  SIGNUP: 'You have signed up successfully.',
  LOGIN: 'You have logged in successfully.',
  GET_ALL_USERS: 'Users retrieved successfully.',
  GET_USER_PROFILE: 'User profile retrieved successfully.',
  GET_USER_BY_ID: 'User retrieved successfully.',
  UPDATE_USER: 'User updated successfully.',
  DELETE_USER: 'User deleted successfully.',
  CREATE_SPECIALIZATION: 'Specialization created successfully.',
  GET_ALL_SPECIALIZATIONS: 'Specializations retrieved successfully.',
  UPDATE_SPECIALIZATION: 'Specialization updated successfully.',
  GET_SPECIALIZATION_BY_ID: 'Specialization retrieved successfully.',
  DELETE_SPECIALIZATION: 'Specialization deleted successfully.',
  UPDATE_DOCTOR: 'Doctor updated successfully.',
  GET_ALL_DOCTORS: 'Doctors retrieved successfully.',
  GET_DOCTOR_BY_ID: 'Doctor retrieved successfully.',
  DELETE_DOCTOR: 'Doctor deleted successfully.',
  UPDATE_USER_PROFILE: 'User profile updated successfully.',
  FORGET_PASSWORD: 'Password reset link sent successfully.',
  RESET_PASSWORD: 'Password reset successfully.',
  SEND_EMAIL_SUCCESS: 'Email sent successfully.',
  SEND_WELCOME_EMAIL_SUCCESS: 'Welcome To DPA Booking!',
  SEND_RESET_PASSWORD_EMAIL_SUCCESS: 'DPA Booking - Reset Password Request',
  SEND_PASSWORD_SET_EMAIL_SUCCESS: 'DPA Booking - Password Reset Successful',
  SEND_EMAIL_WITH_TEMPLATE_SUCCESS: 'Email sent with template successfully.',
};

export const ERROR_MESSAGE = {
  CONVERT_PLAIN_TEXT_TO_HASH: 'An error occurred while converting plain text to a hashed format.',
  SIGNUP: 'An unexpected error occurred during the signup process.',
  SIGNUP_FAILURE: 'Signup failed due to an error.',
  FIND_BY_EMAIL_FAILURE: 'An error occurred while searching for the user by email.',
  EMAIL_ALREADY_EXISTS: 'This email is already associated with an existing account.',
  COMPARE_PASSWORD: 'An error occurred while verifying the password.',
  JWT_SECRET_NOT_SET: 'The JWT secret key is not configured in the environment variables.',
  GENERATE_TOKEN: 'An error occurred while generating the authentication token.',
  INVALID_CREDENTIALS: 'The provided credentials are invalid.',
  USER_NOT_FOUND: 'No user was found with the provided details.',
  LOGIN: 'An unexpected error occurred during the login process.',
  PHONE_NUMBER_ALREADY_EXISTS: 'This phone number is already associated with an existing account.',
  FIND_BY_PHONE_NUMBER_FAILURE: 'An error occurred while searching for the user by phone number.',
  FIND_USER_FAILURE: 'An error occurred while retrieving user details.',
  UNAUTHORIZED_ACCESS: 'You do not have the necessary permissions to perform this operation.',
  UPDATE_CREATE_BY_FAILURE: 'An error occurred while updating the created_by or last_modified_by fields.',
  GET_ALL_USERS: 'An error occurred while retrieving the list of users.',
  GET_USER_PROFILE: 'An error occurred while retrieving the user profile.',
  GET_USER_BY_ID: 'An error occurred while retrieving the user by ID.',
  UPDATE_USER: 'An error occurred while updating the user.',
  NO_USERS_FOUND: 'No users were found in the database.',
  DELETE_USER: 'An error occurred while deleting the user.',
  DOCTOR_SIGNUP_FAILURE: 'An error occurred during the doctor signup process.',
  SPECIALIZATION_ALREADY_EXISTS: 'A specialization with the provided name already exists.',
  GET_SPECIALIZATION_BY_NAME: 'An error occurred while retrieving the specialization by name.',
  CREATE_SPECIALIZATION: 'An error occurred while creating the specialization.',
  NO_SPECIALIZATIONS_FOUND: 'No specializations were found in the database.',
  GET_ALL_SPECIALIZATIONS: 'An error occurred while retrieving the list of specializations.',
  GET_SPECIALIZATION_BY_ID: 'An error occurred while retrieving the specialization by ID.',
  SPECIALIZATION_NOT_FOUND: 'The requested specialization was not found in the database.',
  UPDATE_SPECIALIZATION: 'An error occurred while updating the specialization.',
  DELETE_SPECIALIZATION: 'An error occurred while deleting the specialization.',
  DOCTOR_NOT_FOUND: 'The requested doctor was not found in the database.',
  UPDATE_DOCTOR: 'An error occurred while updating the doctor.',
  DOCTOR_META_NOT_FOUND: 'The requested doctor meta was not found in the database.',
  NO_DOCTORS_FOUND: 'No doctors were found in the database.',
  GET_ALL_DOCTORS: 'An error occurred while retrieving the list of doctors.',
  GET_DOCTOR_BY_ID: 'An error occurred while retrieving the doctor by ID.',
  DELETE_DOCTOR: 'An error occurred while deleting the doctor.',
  UPDATE_USER_PROFILE: 'An error occurred while updating the user profile.',
  FORGET_PASSWORD: 'An error occurred while resetting the password.',
  RESET_PASSWORD_TOKEN_EXPIRED: 'Invalid or expired token',
  UPDATE_PASSWORD_FAILURE: 'An error occurred while updating the password.',
  RESET_PASSWORD: 'An error occurred while resetting the password.',
  SEND_EMAIL_FAILURE: 'An error occurred while sending the email.',
  SEND_WELCOME_EMAIL_FAILURE: 'An error occurred while sending the welcome email.',
  SEND_RESET_PASSWORD_EMAIL_FAILURE: 'An error occurred while sending the reset password email.',
  SEND_PASSWORD_SET_EMAIL_FAILURE: 'An error occurred while sending the password set email.',
  SEND_EMAIL_WITH_TEMPLATE_FAILURE: 'An error occurred while sending the email with template.',
};

export const VALIDATION_ERROR_MESSAGE = {
  FIRST_NAME_REQUIRED: 'Please enter your first name.',
  FIRST_NAME_MIN_LENGTH: 'First name must be at least 3 characters long.',
  FIRST_NAME_MAX_LENGTH: 'First name must not exceed 30 characters.',
  FIRST_NAME_ALPHANUMERIC: 'First name should contain only letters and numbers.',
  LAST_NAME_REQUIRED: 'Please enter your last name.',
  LAST_NAME_MIN_LENGTH: 'Last name must be at least 3 characters long.',
  LAST_NAME_MAX_LENGTH: 'Last name must not exceed 30 characters.',
  LAST_NAME_ALPHANUMERIC: 'Last name should contain only letters and numbers.',
  EMAIL_REQUIRED: 'Please enter a valid email address.',
  EMAIL_INVALID: 'The email format is invalid. Please provide a valid email.',
  PASSWORD_REQUIRED: 'Please enter a password.',
  PASSWORD_MIN_LENGTH: 'Password must be at least 8 characters long.',
  PASSWORD_MAX_LENGTH: 'Password must not exceed 30 characters.',
  PHONE_NUMBER_REQUIRED: 'Please enter your phone number.',
  PHONE_NUMBER_INVALID: 'Phone number must be between 10 and 15 digits.',
  ROLE_REQUIRED: 'Please specify a user role.',
  ROLE_INVALID: 'The provided role is invalid.',
  DATE_OF_BIRTH_REQUIRED: 'Please enter your date of birth.',
  DATE_OF_BIRTH_INVALID: 'The date of birth format is invalid. Please enter a valid date.',
  GENDER_REQUIRED: 'Please select your gender.',
  GENDER_INVALID: 'The selected gender is invalid.',
  IS_ACTIVE_REQUIRED: 'Please specify whether the user is active or not.',
  MEDICAL_LICENSE_NUMBER_REQUIRED: 'Please enter your medical license number.',
  MEDICAL_LICENSE_NUMBER_INVALID:
    'The medical license number format is invalid. Please enter a valid license number. It should be a 10 to 15 digit number.',
  SPECIALIZATION_REQUIRED: 'Please select your specialization.',
  QUALIFICATION_REQUIRED: 'Please enter your qualification.',
  YEAR_OF_EXPERIENCE_REQUIRED: 'Please enter your year of experience.',
  CONSULTATION_FEE_REQUIRED: 'Please enter your consultation fee.',
  AVERAGE_RATING_REQUIRED: 'Please enter your average rating.',
  TOTAL_REVIEWS_REQUIRED: 'Please enter the total number of reviews.',
  CLINIC_ADDRESS_REQUIRED: 'Please enter your clinic address.',
  CITY_REQUIRED: 'Please enter your city.',
  STATE_REQUIRED: 'Please enter your state.',
  COUNTRY_REQUIRED: 'Please enter your country.',
  SPECIALIZATION_NAME_REQUIRED: 'Please enter specialization name.',
  SPECIALIZATION_NAME_MIN_LENGTH: 'Specialization name must be at least 3 characters long.',
  SPECIALIZATION_NAME_MAX_LENGTH: 'Specialization name must not exceed 30 characters.',
  DESCRIPTION_MAX_LENGTH: 'Description must not exceed 255 characters.',
};
